name: checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 9.1.3
      - run: pnpm install
      - run: pnpm type:check
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 9.1.3
      - run: pnpm install
      - run: pnpm format:check
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 9.1.3
      - run: pnpm install
      - run: pnpm lint:check
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: pnpm/action-setup@v2.0.1
  #       with:
  #         version: 9.1.3
  #     - run: pnpm install
  #     - run: pnpm test:all
